import { useEffect, useState } from 'react'
import { Download, Eye, GitCompareArrows, List, Network, Search, SlidersHorizontal } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import type { Document } from '../../domain'
import { documentService } from '../../services/mock'
import AppLayout from '../../layouts/AppLayout'
import { Badge, Btn, Card, EmptyState, Input, PageHeader, Select, Tabs } from '../../components/shared'
import { DemoStateBoundary } from '../SystemPages'

const statusLabel: Record<string, string> = { EFFECTIVE: 'Đang có hiệu lực', PARTIALLY_EFFECTIVE: 'Còn hiệu lực một phần', FUTURE_EFFECTIVE: 'Chưa hiệu lực', EXPIRED: 'Hết hiệu lực', SUPERSEDED: 'Đã thay thế' }
function useDocuments() { const [documents, setDocuments] = useState<Document[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { documentService.list().then(value => { setDocuments(value); setLoading(false) }) }, []); return { documents, loading } }

export function DocumentSearchPage() {
  const { documents, loading } = useDocuments(); const navigate = useNavigate(); const [query, setQuery] = useState(''); const [type, setType] = useState(''); const [status, setStatus] = useState(''); const [filters, setFilters] = useState(false)
  const rows = documents.filter(doc => (!query || `${doc.name} ${doc.code}`.toLowerCase().includes(query.toLowerCase())) && (!type || doc.type === type) && (!status || doc.effectiveStatus === status))
  return <DemoStateBoundary title="Tra cứu văn bản"><AppLayout pageTitle="Tra cứu văn bản"><PageHeader title="Tra cứu văn bản" subtitle="Tìm kiếm trên kho văn bản theo quyền truy cập" /><Card className="p-4 mb-4"><div className="flex gap-2"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-2.5 text-gray-400" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Nhập tên, số hiệu hoặc nội dung văn bản..." className="w-full border rounded pl-9 pr-3 py-2 text-sm" /></div><Btn variant="outline" onClick={() => setFilters(v => !v)}><SlidersHorizontal size={14} /> Bộ lọc</Btn><Btn><Search size={14} /> Tìm kiếm</Btn></div>{filters && <div className="grid grid-cols-5 gap-3 mt-4 pt-4 border-t"><Select label="Loại văn bản" value={type} onChange={setType} options={[{ value: '', label: 'Tất cả' }, ...['Quyết định', 'Quy chế', 'Hướng dẫn'].map(value => ({ value, label: value }))]} /><Input label="Đơn vị ban hành" placeholder="Tất cả đơn vị" /><Input label="Lĩnh vực" placeholder="Tất cả lĩnh vực" /><Input label="Ngày hiệu lực từ" type="date" /><Select label="Hiệu lực" value={status} onChange={setStatus} options={[{ value: '', label: 'Tất cả' }, { value: 'EFFECTIVE', label: 'Đang hiệu lực' }, { value: 'PARTIALLY_EFFECTIVE', label: 'Một phần' }]} /></div>}</Card>
    <div className="space-y-3">{loading ? <div className="animate-pulse h-28 bg-white rounded" /> : rows.length === 0 ? <Card><EmptyState title="Không tìm thấy văn bản" /></Card> : rows.map(doc => <Card key={doc.id} className="p-4 flex items-start gap-4"><div className="w-11 h-11 rounded bg-red-50 text-[#C8102E] grid place-items-center"><List size={20} /></div><div className="flex-1 min-w-0"><button onClick={() => navigate(`/bank-employee/documents/${doc.id}`)} className="font-semibold text-sm hover:text-[#C8102E] text-left">{doc.name}</button><div className="text-xs font-mono text-gray-400 mt-1">{doc.code} · {doc.type} · {doc.issuingUnit}</div><p className="text-xs text-gray-600 mt-2 line-clamp-2">{doc.description} Nội dung phù hợp với truy vấn được hiển thị tại đây để người dùng đánh giá nhanh.</p><div className="flex gap-2 mt-2"><Badge variant={doc.effectiveStatus === 'EFFECTIVE' ? 'effective' : 'warning'} label={statusLabel[doc.effectiveStatus]} /><span className="text-[10px] text-gray-400">Hiệu lực: {doc.effectiveAt}</span></div></div><div className="flex gap-2"><Btn variant="outline" size="sm" onClick={() => navigate(`/bank-employee/documents/${doc.id}`)}><Eye size={13} /> Chi tiết</Btn><Btn variant="ghost" size="sm"><Download size={13} /> Tải gốc</Btn></div></Card>)}</div>
  </AppLayout></DemoStateBoundary>
}

export function ClauseSearchPage() { const { documents } = useDocuments(); const navigate = useNavigate(); const [query, setQuery] = useState(''); const clauses = documents.flatMap(doc => doc.clauses.map(clause => ({ doc, clause }))).filter(item => !query || `${item.clause.content} ${item.clause.path}`.toLowerCase().includes(query.toLowerCase())); return <DemoStateBoundary title="Tìm theo điều khoản"><AppLayout pageTitle="Tìm theo điều khoản"><PageHeader title="Tìm theo điều khoản" subtitle="Tra cứu đến cấp chương, điều, khoản và điểm" /><Card className="p-4 mb-4"><div className="grid grid-cols-6 gap-3"><div className="col-span-2"><Input label="Nội dung tìm kiếm" value={query} onChange={setQuery} placeholder="Nhập nội dung điều khoản..." /></div><Input label="Số điều" placeholder="Ví dụ: 12" /><Input label="Số khoản" placeholder="Ví dụ: 2" /><Input label="Điểm" placeholder="Ví dụ: a" /><Select label="Hiệu lực" options={[{ value: '', label: 'Tất cả' }, { value: 'effective', label: 'Đang hiệu lực' }]} /></div></Card><div className="space-y-3">{clauses.map(({ doc, clause }) => <Card key={clause.id} className="p-4"><div className="flex justify-between"><div><div className="text-xs text-[#C8102E] font-mono">{doc.code}</div><h3 className="font-semibold text-sm mt-1">{doc.name}</h3><div className="text-xs font-medium text-blue-700 mt-2">{clause.path}</div></div><Badge variant="effective" /></div><p className="text-sm leading-6 text-gray-700 bg-gray-50 rounded p-3 mt-3">{clause.content}</p><div className="flex gap-2 mt-3"><Btn size="sm" onClick={() => navigate(`/bank-employee/documents/${doc.id}`)}>Chi tiết</Btn><Btn size="sm" variant="outline" onClick={() => navigate('/bank-employee/timeline')}>Timeline</Btn><Btn size="sm" variant="outline" onClick={() => navigate('/bank-employee/compare')}>So sánh</Btn><Btn size="sm" variant="ghost"><Download size={13} /> Tải gốc</Btn></div></Card>)}</div></AppLayout></DemoStateBoundary> }

export function DocumentDetailPageNew() {
  const { id = 'doc-1' } = useParams(); const [doc, setDoc] = useState<Document>(); const [tab, setTab] = useState('overview'); const [contentQuery, setContentQuery] = useState(''); useEffect(() => { documentService.get(id).then(setDoc) }, [id]); if (!doc) return <AppLayout pageTitle="Chi tiết văn bản"><div className="animate-pulse h-60 bg-white rounded" /></AppLayout>
  return <DemoStateBoundary title="Chi tiết văn bản"><AppLayout pageTitle="Chi tiết văn bản" breadcrumbs={['Tra cứu văn bản', doc.code]}><Card className="p-5 mb-4 flex justify-between"><div><h2 className="font-bold">{doc.name}</h2><div className="text-xs font-mono text-gray-400 mt-1">{doc.code} · {doc.type} · {doc.issuingUnit}</div><div className="mt-2"><Badge variant="effective" label={statusLabel[doc.effectiveStatus]} /></div></div><Btn variant="outline"><Download size={14} /> Tải văn bản gốc</Btn></Card><Card><Tabs tabs={[{ key: 'overview', label: 'Tổng quan' }, { key: 'content', label: 'Nội dung' }, { key: 'clauses', label: 'Điều khoản', count: doc.clauses.length }, { key: 'versions', label: 'Phiên bản', count: doc.versions.length }, { key: 'timeline', label: 'Timeline sửa đổi' }, { key: 'related', label: 'Văn bản liên quan' }]} active={tab} onChange={setTab} />
    {tab === 'overview' && <div className="p-5 grid grid-cols-3 gap-5">{[['Tên văn bản', doc.name], ['Số hiệu', doc.code], ['Loại', doc.type], ['Đơn vị ban hành', doc.issuingUnit], ['Ngày ban hành', doc.issuedAt], ['Ngày hiệu lực', doc.effectiveAt], ['Trạng thái', statusLabel[doc.effectiveStatus]], ['Lĩnh vực', doc.field], ['Từ khóa', doc.keywords.join(', ')]].map(([label, value]) => <div key={label}><div className="text-xs text-gray-400">{label}</div><div className="text-sm font-medium mt-1">{value}</div></div>)}</div>}
    {tab === 'content' && <div className="flex h-[520px]"><aside className="w-60 border-r p-3 overflow-y-auto"><div className="font-semibold text-xs mb-3">Mục lục</div>{['Chương I. Quy định chung', 'Điều 1. Phạm vi', 'Chương II. Nội dung', 'Điều 5. Lãi suất', 'Khoản 2. Kỳ hạn 12 tháng'].map(text => <button key={text} className="block text-left w-full text-xs p-2 hover:bg-gray-50">{text}</button>)}</aside><article className="flex-1 p-5 overflow-y-auto"><div className="relative mb-4"><Search size={15} className="absolute left-2.5 top-2 text-gray-400" /><input value={contentQuery} onChange={e => setContentQuery(e.target.value)} placeholder="Tìm trong văn bản..." className="border rounded pl-8 pr-3 py-1.5 text-xs w-72" /></div><h2 className="font-bold text-center">{doc.name.toUpperCase()}</h2><p className="mt-5 text-sm leading-7">Căn cứ các quy định pháp luật hiện hành và quy chế hoạt động của Ngân hàng TMCP Sài Gòn – Hà Nội;</p><h3 className="font-bold mt-5">Điều 5. Quy định áp dụng</h3><p className={`mt-2 text-sm leading-7 ${contentQuery ? 'bg-yellow-100' : ''}`}>{doc.clauses[0]?.content}</p></article></div>}
    {tab === 'clauses' && <div className="p-5 space-y-3">{doc.clauses.map(clause => <div key={clause.id} className="border rounded p-4"><div className="font-semibold text-sm text-blue-700">{clause.path}</div><p className="text-sm mt-2">{clause.content}</p></div>)}</div>}
    {tab === 'versions' && <div className="p-5 space-y-3">{doc.versions.map(version => <div key={version.id} className="border rounded p-4 flex items-center"><div className="flex-1"><div className="font-semibold text-sm">{version.label}</div><div className="text-xs text-gray-400">{version.effectiveFrom} – {version.effectiveTo || 'Hiện tại'} · {version.changeDocument}</div></div><Badge variant={version.status === 'EFFECTIVE' ? 'effective' : 'superseded'} /><input type="checkbox" className="ml-3" aria-label={`Chọn ${version.label} để so sánh`} /></div>)}</div>}
    {tab === 'timeline' && <TimelineList documents={[doc]} />}{tab === 'related' && <RelationList documents={[doc]} />}
  </Card></AppLayout></DemoStateBoundary>
}

function TimelineList({ documents }: { documents: Document[] }) { return <div className="p-5">{documents.flatMap(doc => doc.timeline).map(event => <div key={event.id} className="flex gap-4 pb-5"><div className="flex flex-col items-center"><div className="w-3 h-3 rounded-full bg-[#C8102E] mt-1" /><div className="w-px bg-gray-200 flex-1" /></div><div className="border rounded p-4 flex-1"><div className="flex justify-between"><h3 className="font-semibold text-sm">{event.type} · {event.clause}</h3><span className="text-xs font-mono text-gray-400">{event.date}</span></div><div className="text-xs text-gray-500 mt-1">Văn bản tạo thay đổi: {event.document}</div><div className="grid grid-cols-2 gap-3 mt-3"><div className="bg-red-50 text-red-700 p-3 rounded text-xs"><b>Trước:</b> {event.before}</div><div className="bg-green-50 text-green-700 p-3 rounded text-xs"><b>Sau:</b> {event.after}</div></div></div></div>)}</div> }
function RelationList({ documents }: { documents: Document[] }) { return <div className="p-5 space-y-3">{documents.flatMap(doc => doc.relations).map(relation => <div key={relation.id} className="border rounded p-4 flex items-center"><div className="w-10 h-10 rounded bg-purple-50 text-purple-700 grid place-items-center"><Network size={18} /></div><div className="flex-1 ml-3"><div className="font-semibold text-sm">{relation.targetDocument}</div><div className="text-xs text-gray-400">{relation.type} · Áp dụng từ {relation.startDate}</div></div><Badge variant="approved" label={relation.type} /></div>)}</div> }

export function ComparePage() { const { documents } = useDocuments(); const doc = documents[0]; const [onlyDiff, setOnlyDiff] = useState(true); const [swapped, setSwapped] = useState(false); if (!doc) return <AppLayout pageTitle="So sánh phiên bản" />; const pair = swapped ? [doc.versions[0], doc.versions[1]] : [doc.versions[1], doc.versions[0]]; return <DemoStateBoundary title="So sánh phiên bản"><AppLayout pageTitle="So sánh phiên bản"><PageHeader title="So sánh phiên bản" subtitle={doc.name} actions={<><label className="text-xs flex items-center gap-2"><input type="checkbox" checked={onlyDiff} onChange={e => setOnlyDiff(e.target.checked)} /> Chỉ phần khác nhau</label><Btn variant="outline" onClick={() => setSwapped(v => !v)}><GitCompareArrows size={14} /> Đổi vị trí</Btn></>} /><div className="grid grid-cols-2 gap-4">{pair.map((version, index) => <Card key={`${version.id}-${index}`}><div className="p-4 border-b"><div className="text-[10px] text-gray-400">PHIÊN BẢN {index ? 'B' : 'A'}</div><div className="font-semibold">{version.label}</div><div className="text-xs text-gray-400">Hiệu lực từ {version.effectiveFrom}</div></div><div className="p-5 text-sm leading-7">Lãi suất kỳ hạn 12 tháng là <mark className={index ? 'bg-green-200' : 'bg-red-200 line-through'}>{version.content.match(/[0-9],[0-9]%/)?.[0]}</mark> tại quầy. {onlyDiff ? '' : 'Các nội dung khác của văn bản được giữ nguyên.'}</div></Card>)}</div></AppLayout></DemoStateBoundary> }
export function TimelinePage() { const { documents } = useDocuments(); return <DemoStateBoundary title="Timeline sửa đổi"><AppLayout pageTitle="Timeline sửa đổi"><PageHeader title="Timeline sửa đổi" subtitle="Theo dõi thay đổi của văn bản và điều khoản" /><Card><TimelineList documents={documents.slice(0, 4)} /></Card></AppLayout></DemoStateBoundary> }
export function RelatedPage() { const { documents } = useDocuments(); const [view, setView] = useState<'list' | 'graph'>('list'); return <DemoStateBoundary title="Văn bản liên quan"><AppLayout pageTitle="Văn bản liên quan"><PageHeader title="Văn bản liên quan" subtitle="Quan hệ tham chiếu, sửa đổi và thay thế" actions={<div className="flex border rounded"><button onClick={() => setView('list')} className={`p-2 ${view === 'list' ? 'bg-gray-100' : ''}`}><List size={15} /></button><button onClick={() => setView('graph')} className={`p-2 ${view === 'graph' ? 'bg-gray-100' : ''}`}><Network size={15} /></button></div>} /><Card>{view === 'list' ? <RelationList documents={documents.slice(0, 6)} /> : <div className="h-[520px] grid place-items-center bg-[#F8FAFC]"><div className="relative w-[600px] h-[360px]">{documents.slice(0, 6).map((doc, index) => <div key={doc.id} className={`absolute rounded-full grid place-items-center text-white text-xs text-center p-3 ${index === 0 ? 'w-28 h-28 bg-[#C8102E] left-60 top-28' : 'w-24 h-24 bg-[#192B4B]'}`} style={index ? { left: `${(index - 1) * 115}px`, top: `${index % 2 ? 20 : 250}px` } : undefined}>{doc.code}</div>)}</div></div>}</Card></AppLayout></DemoStateBoundary> }
